### PR TITLE
add main field 'body' with split entities

### PR DESCRIPTION
**Pull request by harryurban**
regarding: https://github.com/stroeer/rfb/issues/8

example json for field 'body':

```
{
  "body": [
    {
      "type": "BODY_ENTITY_TYPE_PARAGRAPH",
      "content": "Kremlchef <a href='/themen/putin'>Putin</a> hatte schon früh Druck bei der Entwicklung gemacht. Nach Angaben von Muraschko wird derzeit ein zweiter Impfstoff gegen Sars-CoV-2 klinisch getestet. Weitere sollen folgen."
    },
    {
      "type": "BODY_ENTITY_TYPE_ELEMENT",
      "guid": "234345-45645-45645"
    },
    {
      "type": "BODY_ENTITY_TYPE_PARAGRAPH",
      "content": "Lorem ipsum foo bar"
    },
    {
      "type": "BODY_ENTITY_TYPE_SUB_HEADLINE",
      "content": "Putin startet Rakete"
    },
    {
      "type": "BODY_ENTITY_TYPE_PARAGRAPH",
      "content": "Lorem ipsum foo bar"
    },
    {
      "type": "BODY_ENTITY_TYPE_ELEMENT",
      "guid": "234345-45645-45645"
    }
  ]
}
```

example json for element array with new entities:

```
{
  "elements": [
    {
      "type": "ELEMENT_TYPE_BULLET_LIST",
      "guid": "456456-456456-456456",
      "relations": [
        "inline"
      ],
      "assets": [
        {
          "fields": {
            "list_type": "ordered"
          },
          "type": "ASSET_TYPE_METADATA"
        },
        {
          "fields": {
            "content": "<b>Sie ist kaum wiederzuerkennen: </b><a href=\"/unterhaltung/stars/id_88373216/kelly-osbourne-hat-fast-40-kilo-abgenommen-kaum-wiederzuerkennen.html\">Kelly Osbourne hat fast 40 Kilo abgenommen</a>"
          },
          "type": "ASSET_TYPE_HTML",
          "index": 0
        },
        {
          "fields": {
            "content": "<b>\"Was ist das für ein Tier?\": </b><a href=\"/unterhaltung/stars/id_88357012/rapper-bushido-sieht-voellig-anders-aus-was-ist-das-fuer-ein-tier-.html\">Rapper Bushido sieht völlig anders aus </a>"
          },
          "type": "ASSET_TYPE_HTML",
          "index": 1
        },
        {
          "fields": {
            "content": "<b>\"An den richtigen Stellen\": </b><a href=\"unterhaltung/stars/id_88355598/alexander-klaws-hat-in-einem-monat-elf-kilo-zugenommen-an-muskelmasse.html\">Alexander Klaws hat elf Kilo zugenommen</a>"
          },
          "type": "ASSET_TYPE_HTML",
          "index": 2
        }
      ]
    },
    {
      "type": "ELEMENT_TYPE_EDITORIAL_SOURCES",
      "relations": [
        "fixed_position"
      ],
      "assets": [
        {
          "fields": {
            "content": "<a href='https://www.dpa.de'>Nachrichtenagentur dpa</a>"
          },
          "type": "ASSET_TYPE_HTML",
          "index": 0
        },
        {
          "fields": {
            "content": "Nachrichtenagentur Reuters"
          },
          "type": "ASSET_TYPE_HTML",
          "index": 1
        },
        {
          "fields": {
            "content": "Eigenrecherche"
          },
          "type": "ASSET_TYPE_HTML",
          "index": 2
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Comment by bobaaaaa** [comment]
How to fix failing node tests:

```
nvm install 12
cd node
nvm use

npm install
npm run test -- --u
```

**Comment by harryurban** [comment]
> How to fix failing node tests:
> 
> ```
> nvm install 12
> cd node
> nvm use
> 
> npm install
> npm run test -- --u
> ```

kannst du das in den actions workflow einbauen damit das nicht mehr passiert?

**Comment by bobaaaaa** [comment]
Geht nicht, da du einen commit machen musst. Ich überlege noch einmal ob der Test sinnvoll ist.

**Comment by thisismana** [comment]
Personally, I'd prefer the quite special use case of HTML in JSON/proto **not** to be squeezed into Elements/Assets. Instead introduce some new data structure that can be used for markup efficiently and only use the Elements/Assets where it makes sense (images, videos, oembeds, cites, inline-stuff).

This may be a more future proof approach and would make the API more comprehensible and clean.

**Pull request closed without merging**
