### PR TITLE
feature / docker release action

### PR DESCRIPTION
**Pull request by vmk1vmk**
## What 

Added a Github action workflow to build and publish the `protoc` Docker image when changes to it occurred.

## How

feature: added Github action to release internally used Docker image on push to master to GHCR.

### CODE REVIEW

**Comment by moritzzimmer** [comment]
@vmk1vmk please rebase, otherwise 👍

**Review by moritzzimmer — CHANGES_REQUESTED** [review]
we shouldn't use `latest` but rather build and use images with a specific version, e.g. use the `protoc` version as a tag

**Comment by harryurban** [comment]
> we shouldn't use `latest` but rather build and use images with a specific version, e.g. use the `protoc` version as a tag

but maybe in another PR?
currently we also only tag and use latest. in my opinion this is already an improvement to the current situation regarding automation.
your change request is an improvement on top of that, regarding reproducability.

**Review by harryurban — APPROVED** [review]

**Comment by moritzzimmer** [comment]
> > we shouldn't use `latest` but rather build and use images with a specific version, e.g. use the `protoc` version as a tag
> 
> but maybe in another PR?
> currently we also only tag and use latest. in my opinion this is already an improvement to the current situation regarding automation.
> your change request is an improvement on top of that, regarding reproducability.

we ran into issues while upgrading `grpc_js`, so we moved away from using latest @harryurban , see https://github.com/stroeer/tapir/commit/e7caa19aac8bd39c597fd4606624da2faf372f28

**Review by moritzzimmer — APPROVED** [review]
the hard-coded docker tag should be aligned with a strategy of tagging and releasing new image versions

**Pull request merged**
